services:
  redis:
    image: "bitnami/redis:6.2.14"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis_data:/bitnami/redis/data

  postgres:
    image: pgvector/pgvector:0.6.2-pg16
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dembrane
      POSTGRES_USER: dembrane
      POSTGRES_PASSWORD: dembrane
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  directus:
    build:
      context: ../directus
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    volumes:
      - ../directus/uploads:/directus/uploads
    env_file:
      - ../directus/.env
    environment:
      - PUBLIC_URL=http://localhost:8055
      - PORT=8055
      - SECRET=secret
      - TELEMETRY=false
      - ADMIN_EMAIL=admin@dembrane.com
      - ADMIN_PASSWORD=admin
      - ADMIN_TOKEN=admin
      - DB_CLIENT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dembrane
      - DB_PASSWORD=dembrane
      - DB_DATABASE=dembrane
      - WEBSOCKETS_ENABLED=true
      - CORS_ENABLED=true
      - CORS_ORIGIN=http://localhost:5173,http://localhost:5174
      - CORS_CREDENTIALS=true
      - SESSION_COOKIE_SECURE=false
      - SESSION_COOKIE_SAME_SITE=lax
      - USER_INVITE_URL_ALLOW_LIST=http://localhost:5173/invite
      - USER_REGISTER_URL_ALLOW_LIST=http://localhost:5173/verify-email
      - PASSWORD_RESET_URL_ALLOW_LIST=http://localhost:5173/password-reset
    depends_on:
      - postgres
      - redis

  devcontainer:
    build:
      context: ../server
      dockerfile: Dockerfile
      target: base
    environment:
      - DIRECTUS_SECRET=secret
      - DIRECTUS_TOKEN=admin
      - DATABASE_URL=postgresql+psycopg://dembrane:dembrane@postgres:5432/dembrane
      - REDIS_URL=redis://redis:6379
      - API_BASE_URL=http://localhost:8000
      - ADMIN_BASE_URL=http://localhost:5173
      - PARTICIPANT_BASE_URL=http://localhost:5174
      - DIRECTUS_BASE_URL=http://directus:8055
      - DEBUG_MODE=1
      - DISABLE_SENTRY=1
      - SERVE_API_DOCS=1
      - DISABLE_REDACTION=1
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:postgres
    command: sleep infinity
    depends_on:
      - postgres
      - redis
